# Generated by Django 4.2.23 on 2025-08-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='jira_base_url',
            field=models.URLField(blank=True, help_text='e.g. https://your-domain.atlassian.net'),
        ),
        migrations.AddField(
            model_name='room',
            name='jira_board_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='jira_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='room',
            name='jira_project_key',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='jira_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
