# Generated by Django 5.2.8 on 2025-11-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_room_jira_base_url_room_jira_board_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='jira_issue_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
