# Generated by Django 5.2.8 on 2025-11-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poker", "0003_story_jira_issue_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="jira_estimate",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
