# Generated by Django 5.2.9 on 2025-02-14 12:00

from django.db import migrations

import poker.fields


def encrypt_tokens(apps, schema_editor):
    Room = apps.get_model("poker", "Room")
    for room in Room.objects.all():
        token = room.jira_token
        if not token:
            continue
        room.jira_token = token
        room.save(update_fields=["jira_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("poker", "0004_story_jira_estimate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="jira_token",
            field=poker.fields.EncryptedTextField(blank=True),
        ),
        migrations.RunPython(encrypt_tokens, reverse_code=migrations.RunPython.noop),
    ]
